Lint release script.

diff --git a/release b/release
--- a/release
+++ b/release
@@ -7,47 +7,47 @@ SEMVER=./node_modules/.bin/semver
 PREID=alpha
 
 DIR=$(dirname "${BASH_SOURCE[0]}")
-cd ${DIR}
+cd "${DIR}" || exit
 FAILED=false
 
 run() {
-	msg="$1"
+	local msg="$1"
 	shift
-	cmd="$@"
-	${ECHO} ${msg}
+	local cmdline=("$@")
+	${ECHO} "${msg}"
 	if ${DEBUG}; then
-		echo "> $cmd"
+		echo "> ${cmdline[*]}"
 	elif ${FAILED}; then
-		echo "'${cmd}' skipped due to earlier error."
-    else
-		eval "$cmd" || { echo "Error $? running '${cmd}'"; FAILED=true; }
+		echo "'${cmdline[*]}' skipped due to earlier error."
+	else
+		"${cmdline[@]}" || { echo "Error $? running '${cmdline[*]}'"; FAILED=true; }
 	fi
 }
 
 new() {
-	BRANCH=$(${SEMVER} -i minor ${VERSION})
-	run "Creating release branch ${BRANCH}" git checkout -b ${BRANCH}
+	BRANCH=$(${SEMVER} -i minor "${VERSION}")
+	run "Creating release branch ${BRANCH}" git checkout -b "${BRANCH}"
 	run "Tagging release" npm version minor
 	run "Incrementing master version" git checkout master
-	run "" npm verison $(${SEMVER} --preid ${PREID} -i preminor ${VERSION})
-	run "Pushing to origin" git push origin --tags master ${BRANCH}
-	run "Publishing" git checkout ${BRANCH}
+	run "" npm verison "$(${SEMVER} --preid ${PREID} -i preminor "${VERSION}")"
+	run "Pushing to origin" git push origin --tags master "${BRANCH}"
+	run "Publishing" git checkout "${BRANCH}"
 	run "" npm publish
 	run "" git checkout master
 }
 
 patch() {
 	local release="$2"
-	run "Checking out release branch ${release}" git checkout ${release}
+	run "Checking out release branch ${release}" git checkout "${release}"
 	run "Tagging release" npm version patch
-	run "Pushing to origin" git push origin --tags ${release}
+	run "Pushing to origin" git push origin --tags "${release}"
 	run "Publishing" npm publish
 	run "" git checkout master
 }
 
 major() {
 	run "Incrementing master version" git checkout master
-	run "" npm version $(${SEMVER} --preid ${PREID} -i premajor ${VERSION})
+	run "" npm version "$(${SEMVER} --preid ${PREID} -i premajor "${VERSION}")"
 	run "Pushing to origin" git push origin --tags master
 }
 
